export const LAUNCH_CREATOR_TARGET = 100;
export const MAX_VIDEOS_PER_PROFILE = 2;
export const MAX_VIDEO_BYTES = 40 * 1024 * 1024;
export const MAX_PROFILE_IMAGE_BYTES = 3 * 1024 * 1024;
export const MAX_LAUNCH_MEDIA_BYTES =
  LAUNCH_CREATOR_TARGET * MAX_VIDEOS_PER_PROFILE * MAX_VIDEO_BYTES;
export const MAX_LAUNCH_PROFILE_MEDIA_BYTES =
  LAUNCH_CREATOR_TARGET * 2 * MAX_PROFILE_IMAGE_BYTES;
export const MAX_LAUNCH_STORAGE_BYTES =
  MAX_LAUNCH_MEDIA_BYTES + MAX_LAUNCH_PROFILE_MEDIA_BYTES;
