export const LAUNCH_CREATOR_TARGET = 100;
export const MAX_VIDEOS_PER_PROFILE = 2;
export const MAX_VIDEO_BYTES = 40 * 1024 * 1024;
export const MAX_LAUNCH_MEDIA_BYTES =
  LAUNCH_CREATOR_TARGET * MAX_VIDEOS_PER_PROFILE * MAX_VIDEO_BYTES;

